name: Build ReSukiSU Kernel
on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Workspace
        uses: actions/checkout@v4

      - name: Compile Android Kernel with SukiSU
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/Abineshsm36/t295-resukisu-kernel
          kernel-branch: lineage-22.2
          config: lineageos_gtowifi_defconfig
          arch: arm64
          android-version: 15
          ksu: true
          ksu-other: true
          ksu-url: https://github.com/SukiSU-Ultra/SukiSU-Ultra
          
          # Force a legacy Android toolchain to fix the sdm429.dtb "unknown option" error
          aosp-clang: true
          aosp-clang-version: r383902
          aosp-gcc: true
